name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/my-app:latest .
          docker push ghcr.io/${{ github.repository_owner }}/my-app:latest

      - name: Deploy to Production Server
        run: |
          ssh user@production-server-ip << 'EOF'
            docker pull ghcr.io/${{ github.repository_owner }}/my-app:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d -p 3000:3000 --name my-app ghcr.io/${{ github.repository_owner }}/my-app:latest
          EOF
