# .github/workflows/staging.yml
name: Deploy to Staging

on:
  push:
    branches: [main]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup environment variables
        run: echo "Deploying to STAGING environment"

      - name: Simulate deployment
        run: echo "🚀 Staging deployment successful!"
